### ISSUE TITLE
UI Not Rendering Properly in Forge with Gradio 4.x Integration

### ISSUE THREAD

**Issue by namemechan** [thundaga/SD-webui-txt2img-script#25]
Hello,

I'm encountering an issue where the UI does not render correctly in the latest Forge version when integrating with Gradio 4.x. The same script and UI setup worked flawlessly with Gradio 3.x, but after upgrading to Gradio 4.x, certain UI components, like tabs and file inputs, either break or do not display as expected.

I've attached the relevant code snippets and a screenshot of the issue. Any guidance on how to resolve this or insight into what might be causing the incompatibility would be greatly appreciated.

Thank you!

**Comment by thundaga** [comment]
Script is targeted towards the main webui which is currently under Gradio 3.41.2 rather than 4.40.0 from forge. I cannot update the current implementation of the ui elements because of that.

Provide me the screen shots/error logs and lets see what component is causing the issue.

If you have uploaded the images, I do not see them on your comment.

**Comment by namemechan** [comment]
----------------------------------------------------
*** Error calling: C:\AI\forge\stable-diffusion-webui-forge\scripts\process_png_metadata.py/ui
    Traceback (most recent call last):
      File "C:\AI\forge\stable-diffusion-webui-forge\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "C:\AI\forge\stable-diffusion-webui-forge\scripts\process_png_metadata.py", line 148, in ui
        with gr.Row().style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'
----------------------------------------------------
![스크린샷 2024-08-27 211502](https://github.com/user-attachments/assets/58f30dd4-e1c0-45fb-a486-c14e084930b2)

select a script, it will not be displayed.

**Comment by OPCOXE** [comment]
Yeah the issue comes from the differences between Gradio 3 and Gradio 4.
As I can tell from thier [docs](https://www.gradio.app/main/docs/gradio), "Row" does not have Style anymore but it has equal_height and variant in its initilization parameter so the following line of code : 
`with gr.Row().style(equal_height=False, variant='compact'):`
Should be replaced by : 
`with gr.Row(equal_height=False, variant='compact'):`

Let us know if it worked, also it may just add up another incompatibility error

**Comment by namemechan** [comment]
The ui box has been created, but the contents are not displayed properly.

These are the parts where the error is displayed on the cmd.

scripts\process_png_metadata.py", line 152, in ui
upload_files = gr.File(label="Batch Process", file_count="multiple", interactive=True, type="file", elem_id=self.elem_id("files"))
![batch](https://github.com/user-attachments/assets/bd4d9d91-0509-4f31-bc7e-91f08fd585b3)

**Comment by namemechan** [comment]
![image](https://github.com/user-attachments/assets/4c4b42aa-859c-4aa2-8e5e-2b769f8df57f)

yeah! It's working fine. Thank you for your help!!!
