### ISSUE TITLE
Trivial Bug: "LORA hashes" bleeding into metadata

### ISSUE THREAD

**Issue by altoiddealer** [thundaga/SD-webui-txt2img-script#9]
Hello, thank you again for making this excellent script.

I just noticed that **when the script uses a LORA for an image, every image generated afterwards will include the same "LORA Hash" in the metadata for all further images in the batch** - until it processes an image that has a different LORA.
Then, the bug repeats until there is a different LORA... and so on, and so on.

This doesn't seem to actually have any bearing on the image.  It's just mildly annoying that, if you process thousands of images and one of them has a LORA, then majority of the images will have LORA in the metadata.

*removed mildly NSFW image since you saw it and understand the bug*

**Comment by thundaga** [comment]
Got it I'll look into it by tomorrow 👍. Also you can redact the entire image and comment preceding it.

**Comment by altoiddealer** [comment]
If its any help, I also want to add that I repeated the same without --xformers and have the same result.

I also noticed just how much of an effect --xformers has on batches like this... yikes!  It really has a dramatic effect.  I was about to report another bug, but it's just xformers.

**Comment by OPCOXE** [comment]
Didn't had issues with xformers for me exept the image was different everytime and it was horrible for me since I generate non-Hires fix images then Hires fix then in a batch ...

Anyways, I'm assuming this come from the fact that the script doesn't reset everything between each image. It shouldn't change the output images as I didn't noticed it (I also use different Loras).

**Comment by thundaga** [comment]
@altoiddealer have you tried this on the most recent version, because the latest commit over a week ago should have fixed the extra generation parameters such as a Lora hash in the infoText since its dictionary information is reset after each image.

**Comment by altoiddealer** [comment]
I am definitely on the most recent version of the extension, and it definitely occurs as I described.

Should be pretty easy to reproduce, so long as you have a LORA file... just put 2 images in a folder and make sure the first one had LORA in the prompt.  The second image will have the LORA hash in its metadata

**Comment by thundaga** [comment]
Hmm strange I'm not able to reproduce this, the Lora hashes disappear on the second image for me. can you verify that the extension has this line of code in it on around line 176 "p.extra_generation_params = {}", 
since I can reproduce your issue when that line is gone but unable to when it's there.
also can you try it on the original sd webui.

**Comment by altoiddealer** [comment]
Welp, I apologize for wasting your time with this one.

It turns out that I did not have the most recent version in my scripts folder.  I think I updated the extension 2 weeks ago but failed to copy it over.


...I just retested and there is no issue!

**Comment by thundaga** [comment]
ok awesome 👍
